package model;
// Generated 01.Eki.2019 10:54:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "foodtown")
public class Admin implements java.io.Serializable {

	private Integer aid;
	private String aname;
	private String amail;
	private String apass;
	private String role;
	private String adminpassword;

	public Admin() {
	}

	public Admin(String aname, String amail, String apass) {
		this.aname = aname;
		this.amail = amail;
		this.apass = apass;
	}

	public Admin(String aname, String amail, String apass, String role, String adminpassword) {
		this.aname = aname;
		this.amail = amail;
		this.apass = apass;
		this.role = role;
		this.adminpassword = adminpassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "aid", unique = true, nullable = false)
	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	@Column(name = "aname", nullable = false)
	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	@Column(name = "amail", nullable = false)
	public String getAmail() {
		return this.amail;
	}

	public void setAmail(String amail) {
		this.amail = amail;
	}

	@Column(name = "apass", nullable = false, length = 32)
	public String getApass() {
		return this.apass;
	}

	public void setApass(String apass) {
		this.apass = apass;
	}

	@Column(name = "role", length = 32)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "adminpassword", length = 32)
	public String getAdminpassword() {
		return this.adminpassword;
	}

	public void setAdminpassword(String adminpassword) {
		this.adminpassword = adminpassword;
	}

}
