package model;
// Generated 01.Eki.2019 10:54:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog", catalog = "foodtown")
public class Blog implements java.io.Serializable {

	private Integer postid;
	private String posttitle;
	private String posttext;
	private String postimage;
	private String postauthorimage;
	private String postdate;
	private String postauthor;
	private String posttextparagraph1;
	private String posttextparagraph2;

	public Blog() {
	}

	public Blog(String posttitle, String posttext, String postimage, String postauthorimage, String postdate,
			String postauthor) {
		this.posttitle = posttitle;
		this.posttext = posttext;
		this.postimage = postimage;
		this.postauthorimage = postauthorimage;
		this.postdate = postdate;
		this.postauthor = postauthor;
	}

	public Blog(String posttitle, String posttext, String postimage, String postauthorimage, String postdate,
			String postauthor, String posttextparagraph1, String posttextparagraph2) {
		this.posttitle = posttitle;
		this.posttext = posttext;
		this.postimage = postimage;
		this.postauthorimage = postauthorimage;
		this.postdate = postdate;
		this.postauthor = postauthor;
		this.posttextparagraph1 = posttextparagraph1;
		this.posttextparagraph2 = posttextparagraph2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "postid", unique = true, nullable = false)
	public Integer getPostid() {
		return this.postid;
	}

	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	@Column(name = "posttitle", nullable = false, length = 65535)
	public String getPosttitle() {
		return this.posttitle;
	}

	public void setPosttitle(String posttitle) {
		this.posttitle = posttitle;
	}

	@Column(name = "posttext", nullable = false, length = 65535)
	public String getPosttext() {
		return this.posttext;
	}

	public void setPosttext(String posttext) {
		this.posttext = posttext;
	}

	@Column(name = "postimage", nullable = false, length = 65535)
	public String getPostimage() {
		return this.postimage;
	}

	public void setPostimage(String postimage) {
		this.postimage = postimage;
	}

	@Column(name = "postauthorimage", nullable = false, length = 65535)
	public String getPostauthorimage() {
		return this.postauthorimage;
	}

	public void setPostauthorimage(String postauthorimage) {
		this.postauthorimage = postauthorimage;
	}

	@Column(name = "postdate", nullable = false, length = 65535)
	public String getPostdate() {
		return this.postdate;
	}

	public void setPostdate(String postdate) {
		this.postdate = postdate;
	}

	@Column(name = "postauthor", nullable = false, length = 65535)
	public String getPostauthor() {
		return this.postauthor;
	}

	public void setPostauthor(String postauthor) {
		this.postauthor = postauthor;
	}

	@Column(name = "posttextparagraph1", length = 65535)
	public String getPosttextparagraph1() {
		return this.posttextparagraph1;
	}

	public void setPosttextparagraph1(String posttextparagraph1) {
		this.posttextparagraph1 = posttextparagraph1;
	}

	@Column(name = "posttextparagraph2", length = 65535)
	public String getPosttextparagraph2() {
		return this.posttextparagraph2;
	}

	public void setPosttextparagraph2(String posttextparagraph2) {
		this.posttextparagraph2 = posttextparagraph2;
	}

}
