package model;
// Generated 01.Eki.2019 10:54:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "foodtown")
public class Cart implements java.io.Serializable {

	private Integer cartid;
	private String foodname;
	private double foodprice;
	private String foodstatus;

	public Cart() {
	}

	public Cart(String foodname, double foodprice, String foodstatus) {
		this.foodname = foodname;
		this.foodprice = foodprice;
		this.foodstatus = foodstatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cartid", unique = true, nullable = false)
	public Integer getCartid() {
		return this.cartid;
	}

	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	@Column(name = "foodname", nullable = false)
	public String getFoodname() {
		return this.foodname;
	}

	public void setFoodname(String foodname) {
		this.foodname = foodname;
	}

	@Column(name = "foodprice", nullable = false, precision = 22, scale = 0)
	public double getFoodprice() {
		return this.foodprice;
	}

	public void setFoodprice(double foodprice) {
		this.foodprice = foodprice;
	}

	@Column(name = "foodstatus", nullable = false)
	public String getFoodstatus() {
		return this.foodstatus;
	}

	public void setFoodstatus(String foodstatus) {
		this.foodstatus = foodstatus;
	}

}
