package model;
// Generated 01.Eki.2019 10:54:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contactus generated by hbm2java
 */
@Entity
@Table(name = "contactus", catalog = "foodtown")
public class Contactus implements java.io.Serializable {

	private Integer contactid;
	private String namesurname;
	private String mail;
	private String message;

	public Contactus() {
	}

	public Contactus(String namesurname, String mail, String message) {
		this.namesurname = namesurname;
		this.mail = mail;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "contactid", unique = true, nullable = false)
	public Integer getContactid() {
		return this.contactid;
	}

	public void setContactid(Integer contactid) {
		this.contactid = contactid;
	}

	@Column(name = "namesurname", nullable = false, length = 65535)
	public String getNamesurname() {
		return this.namesurname;
	}

	public void setNamesurname(String namesurname) {
		this.namesurname = namesurname;
	}

	@Column(name = "mail", nullable = false)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
