package model;
// Generated 01.Eki.2019 10:54:35 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Neworder generated by hbm2java
 */
@Entity
@Table(name = "neworder", catalog = "foodtown")
public class Neworder implements java.io.Serializable {

	private Integer orderid;
	private String fullname;
	private String address;
	private String foodname;
	private String foodstatus;
	private String phonenumber;
	private String note;
	private double totalprice;

	public Neworder() {
	}

	public Neworder(String fullname, String address, String foodname, String foodstatus, String phonenumber,
			double totalprice) {
		this.fullname = fullname;
		this.address = address;
		this.foodname = foodname;
		this.foodstatus = foodstatus;
		this.phonenumber = phonenumber;
		this.totalprice = totalprice;
	}

	public Neworder(String fullname, String address, String foodname, String foodstatus, String phonenumber,
			String note, double totalprice) {
		this.fullname = fullname;
		this.address = address;
		this.foodname = foodname;
		this.foodstatus = foodstatus;
		this.phonenumber = phonenumber;
		this.note = note;
		this.totalprice = totalprice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "orderid", unique = true, nullable = false)
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "fullname", nullable = false, length = 65535)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "foodname", nullable = false)
	public String getFoodname() {
		return this.foodname;
	}

	public void setFoodname(String foodname) {
		this.foodname = foodname;
	}

	@Column(name = "foodstatus", nullable = false)
	public String getFoodstatus() {
		return this.foodstatus;
	}

	public void setFoodstatus(String foodstatus) {
		this.foodstatus = foodstatus;
	}

	@Column(name = "phonenumber", nullable = false)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "totalprice", nullable = false, precision = 22, scale = 0)
	public double getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(double totalprice) {
		this.totalprice = totalprice;
	}

}
